name: "setup-headless-display-action"
description: "Setup a headless display on Linux and Windows"
author: PyVista Developers'
inputs:
  pyvista:
    description: "Set PyVista env vars for headless mode"
    required: false
    default: true
  qt:
    description: "Install libraries required for Qt on Linux"
    required: false
    default: false
branding:
  icon: "monitor"
  color: "blue"
runs:
  using: "composite"
  steps:
    - name: Update apt
      if: runner.os == 'Linux'
      shell: bash
      # TODO: Pyvista uses `xset` which is part of x11-xserver-utils, maybe a better way to check?
      run: sudo apt update

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get install -y \
          libglx-mesa0 \
          libgl1 \
          xvfb \
          x11-xserver-utils

    - name: Install Linux Qt dependencies
      if: runner.os == 'Linux' && inputs.qt != 'false'
      shell: bash
      run: |
        sudo apt-get install -y \
          libdbus-1-3 \
          libegl1 \
          libegl1-mesa \
          libopengl0 \
          libosmesa6 \
          libxcb-cursor0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-shape0 \
          libxcb-xfixes0 \
          libxcb-xinerama0 \
          libxcb-xinput0 \
          libxkbcommon-x11-0 \
          mesa-utils \
          x11-utils

    - name: Install Windows GL Dependencies
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        Set-StrictMode -Version Latest
        $ErrorActionPreference = "Stop"
        $PSDefaultParameterValues['*:ErrorAction']='Stop'
        powershell ${{ github.action_path }}/windows/install_opengl.ps1

    - name: Configure headless display on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        export DISPLAY=:99.0
        echo "DISPLAY=:99.0" >> $GITHUB_ENV
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3

    - name: Configure for PyVista
      if: inputs.pyvista != 'false'
      shell: bash
      run: echo "PYVISTA_OFF_SCREEN=true" >> $GITHUB_ENV
